// // change this after running find-js-files.js
// let automatedBlockUrls = [
//   [
//     "logbook.itstep.org/assets/afa84253/swagger-ui/dist/swagger-ui.js",
//     "script",
//     "/js/swagger-ui.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/bootstrap/dist/js/bootstrap.js",
//     "script",
//     "/js/bootstrap.js",
//   ],
//   ["logbook.itstep.org/js/library/d3.js", "script", "/js/d3.js"],
//   [
//     "logbook.itstep.org/assets/afa84253/angular/angular.min.js",
//     "script",
//     "/js/angular.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-ui-router/release/angular-ui-router.min.js",
//     "script",
//     "/js/angular-ui-router.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-animate/angular-animate.min.js",
//     "script",
//     "/js/angular-animate.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-aria/angular-aria.min.js",
//     "script",
//     "/js/angular-aria.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-material/angular-material.min.js",
//     "script",
//     "/js/angular-material.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-messages/angular-messages.min.js",
//     "script",
//     "/js/angular-messages.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-local-storage/dist/angular-local-storage.min.js",
//     "script",
//     "/js/angular-local-storage.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-translate/angular-translate.min.js",
//     "script",
//     "/js/angular-translate.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-toArrayFilter/toArrayFilter.js",
//     "script",
//     "/js/toArrayFilter.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/angular-translate-loader-url/angular-translate-loader-url.min.js",
//     "script",
//     "/js/angular-translate-loader-url.min.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/raven-js/dist/raven.js",
//     "script",
//     "/js/raven.js",
//   ],
//   [
//     "logbook.itstep.org/assets/afa84253/raven-js/dist/plugins/angular.js",
//     "script",
//     "/js/angular.js",
//   ],
//   ["logbook.itstep.org/assets/ee7e365a/chosen.js", "script", "/js/chosen.js"],
//   [
//     "logbook.itstep.org/assets/ee7e365a/angular-chosen.min.js",
//     "script",
//     "/js/angular-chosen.min.js",
//   ],
//   ["logbook.itstep.org/js/angular/script.js", "script", "/js/script.js"],
//   [
//     "logbook.itstep.org/js/angular/create-graph.js",
//     "script",
//     "/js/create-graph.js",
//   ],
//   [
//     "logbook.itstep.org/js/angular/directives.js",
//     "script",
//     "/js/directives.js",
//   ],
//   [
//     "logbook.itstep.org/js/angular/base-factory.js",
//     "script",
//     "/js/base-factory.js",
//   ],
//   [
//     "logbook.itstep.org/js/angular/base-controller.js",
//     "script",
//     "/js/base-controller.js",
//   ],
//   [
//     "logbook.itstep.org/js/angular/signal/controllers/signalCtrl.js",
//     "script",
//     "/js/signalCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/js/angular/signal/signal-factory.js",
//     "script",
//     "/js/signal-factory.js",
//   ],
//   [
//     "logbook.itstep.org/js/angular/signal/signal-filters.js",
//     "script",
//     "/js/signal-filters.js",
//   ],
//   [
//     "logbook.itstep.org/assets/aeb712a2/controllers/classWorkCtrl.js",
//     "script",
//     "/js/classWorkCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/aeb712a2/classwork-factory.js",
//     "script",
//     "/js/classwork-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/e69d4368/controllers/examsCtrl.js",
//     "script",
//     "/js/examsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/e69d4368/exams-factory.js",
//     "script",
//     "/js/exams-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/e69d4368/controllers/courseWorksCtrl.js",
//     "script",
//     "/js/courseWorksCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/c285501/controllers/homeWorkCtrl.js",
//     "script",
//     "/js/homeWorkCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/c285501/homeworks-factory.js",
//     "script",
//     "/js/homeworks-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/c285501/homeworks-filters.js",
//     "script",
//     "/js/homeworks-filters.js",
//   ],
//   [
//     "logbook.itstep.org/assets/2dbcf43b/controllers/individualCtrl.js",
//     "script",
//     "/js/individualCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/2dbcf43b/individual-factory.js",
//     "script",
//     "/js/individual-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/972c11f7/controllers/newsCtrl.js",
//     "script",
//     "/js/newsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/972c11f7/news-factory.js",
//     "script",
//     "/js/news-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/e64e2540/controllers/profileCtrl.js",
//     "script",
//     "/js/profileCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/e64e2540/profile-factory.js",
//     "script",
//     "/js/profile-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/cc4b8ae1/report.helper.js",
//     "script",
//     "/js/report.helper.js",
//   ],
//   [
//     "logbook.itstep.org/assets/cc4b8ae1/controllers/reportCtrl.js",
//     "script",
//     "/js/reportCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/cc4b8ae1/report-factory.js",
//     "script",
//     "/js/report-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/ca612b01/schedule.helper.js",
//     "script",
//     "/js/schedule.helper.js",
//   ],
//   [
//     "logbook.itstep.org/assets/ca612b01/controllers/scheduleCtrl.js",
//     "script",
//     "/js/scheduleCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/ca612b01/schedule_factory.js",
//     "script",
//     "/js/schedule_factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/controllers/mainStudCtrl.js",
//     "script",
//     "/js/mainStudCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/controllers/sendStudentsMailCtrl.js",
//     "script",
//     "/js/sendStudentsMailCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/controllers/studentsCommentCtrl.js",
//     "script",
//     "/js/studentsCommentCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/controllers/studentsCtrl.js",
//     "script",
//     "/js/studentsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/controllers/studentProfileCtrl.js",
//     "script",
//     "/js/studentProfileCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/students-module.js",
//     "script",
//     "/js/students-module.js",
//   ],
//   [
//     "logbook.itstep.org/assets/abb306eb/students-factory.js",
//     "script",
//     "/js/students-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/f3f1f0cb/controllers/tasksCtrl.js",
//     "script",
//     "/js/tasksCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/f3f1f0cb/tasks-factory.js",
//     "script",
//     "/js/tasks-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/bind_factory.js",
//     "script",
//     "/js/bind_factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/bindFormsCtrl.js",
//     "script",
//     "/js/bindFormsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/bindMainCtrl.js",
//     "script",
//     "/js/bindMainCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/bindMaterialsCtrl.js",
//     "script",
//     "/js/bindMaterialsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/bindTeachMaterialsCtrl.js",
//     "script",
//     "/js/bindTeachMaterialsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/bindCityCtrl.js",
//     "script",
//     "/js/bindCityCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/linkingMainCtrl.js",
//     "script",
//     "/js/linkingMainCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/linkingMethodCtrl.js",
//     "script",
//     "/js/linkingMethodCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/linkingSpecCtrl.js",
//     "script",
//     "/js/linkingSpecCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/bindAuthorsCtrl.js",
//     "script",
//     "/js/bindAuthorsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/linkingFormCtrl.js",
//     "script",
//     "/js/linkingFormCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logsCtrl.js",
//     "script",
//     "/js/logsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/linkingDirectionCtrl.js",
//     "script",
//     "/js/linkingDirectionCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/linkingEditSpecCtrl.js",
//     "script",
//     "/js/linkingEditSpecCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logs/materialsLogsCtrl.js",
//     "script",
//     "/js/materialsLogsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logs/methodPackageLogsCtrl.js",
//     "script",
//     "/js/methodPackageLogsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logs/mainLogsCtrl.js",
//     "script",
//     "/js/mainLogsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logs/methodLinkingLogsCtrl.js",
//     "script",
//     "/js/methodLinkingLogsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logs/methodBindLogsCtrl.js",
//     "script",
//     "/js/methodBindLogsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/controllers/logs/methodPublicSpecLogsCtrl.js",
//     "script",
//     "/js/methodPublicSpecLogsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/8265d3f0/logs_factory.js",
//     "script",
//     "/js/logs_factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/c80f60db/controllers/groupsCtrl.js",
//     "script",
//     "/js/groupsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/c80f60db/groups-factory.js",
//     "script",
//     "/js/groups-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/66e93df1/controllers/portfolioCtrl.js",
//     "script",
//     "/js/portfolioCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/66e93df1/portfolio-factory.js",
//     "script",
//     "/js/portfolio-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/319d99bd/presents_factory.js",
//     "script",
//     "/js/presents_factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/319d99bd/controllers/presentsCtrl.js",
//     "script",
//     "/js/presentsCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/319d99bd/controllers/addMaterialCtrl.js",
//     "script",
//     "/js/addMaterialCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/319d99bd/controllers/addHomeWorkCtrl.js",
//     "script",
//     "/js/addHomeWorkCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/319d99bd/controllers/addLabWorkCtrl.js",
//     "script",
//     "/js/addLabWorkCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/6b1bc118/home/controllers/homeCtrl.js",
//     "script",
//     "/js/homeCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/6b1bc118/home/home-factory.js",
//     "script",
//     "/js/home-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/6b1bc118/dateService.js",
//     "script",
//     "/js/dateService.js",
//   ],
//   [
//     "logbook.itstep.org/assets/7324b17d/controllers/certificatesCtrl.js",
//     "script",
//     "/js/certificatesCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/7324b17d/certificates_factory.js",
//     "script",
//     "/js/certificates_factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/a9351143/controllers/dossierCtrl.js",
//     "script",
//     "/js/dossierCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/a9351143/dossier-factory.js",
//     "script",
//     "/js/dossier-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/7b70dfc0/controllers/TraficCtrl.js",
//     "script",
//     "/js/TraficCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/7b70dfc0/traffic-factory.js",
//     "script",
//     "/js/traffic-factory.js",
//   ],
//   [
//     "logbook.itstep.org/assets/7d27e970/controllers/contentAuthorCtrl.js",
//     "script",
//     "/js/contentAuthorCtrl.js",
//   ],
//   [
//     "logbook.itstep.org/assets/7d27e970/content-factory.js",
//     "script",
//     "/js/content-factory.js",
//   ],
// ];

// export { automatedBlockUrls };
